name: YOLOv8 Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: nvidia

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag yolov8-docker .
